### ISSUE TITLE
ir_sim中的agent可以使用角速度和线速度控制吗？

### ISSUE THREAD

**Issue by 630732041** [hanruihua/ir_sim#8]

**Comment by hanruihua** [comment]
可以的  参考例子  https://github.com/hanruihua/ir_sim/blob/main/ir_sim/usage/02robot_world/robot_world.py   

机器人的动力学默认是 diff  差速轮  就是用角速度和线速度控制的

**Comment by 630732041** [comment]
好的，感谢回复
